image_base: seed/alessi-mutants
project_name: tester
global:
  web:
    environment:
      - NODE_ENV=something    
dev:
  web:
    environment:
      - NODE_ENV=dev
    labels:
      io.rancher.scheduler.affinity:host_label: client=ibackpacker,env=development
staging:
  web:
    environment:
      - NODE_ENV=staging
    labels:
    #   io.rancher.scheduler.affinity:host_label: client=alessi,env=staging
      com.alessimutants.pods: version=0.1,branch=dev
prod:
  lb:
    labels:
      io.rancher.scheduler.local: 'false'
  web:
    image: seed/web
    environment:
      - NODE_ENV=prod
      - BLAH=prod
      - TWO_ENV=prod
    labels:
      io.rancher.scheduler.local: 'false'
