lb:
  image: rancher/load-balancer-service
  ports:
    - "443:3000"
  restart: always
  links:
    - web:web
  labels:
    io.rancher.scheduler.global: 'true'
    io.rancher.loadbalancer.ssl.ports: '443'
  tty: true
  image: rancher/load-balancer-service
  stdin_open: true

nginx-https-redirect:
  image: jamessharp/docker-nginx-https-redirect
  ports:
    - "80:80"
  labels:
    io.rancher.scheduler.global: 'true'

web:
  image: seed/ibackpacker_dev:development # NEEDS TO BE TEMPLATED OUT
  extends:
    file: common.dev.yml #NEEDS TO BE TEMPLATED OUT
    service: web
  expose:
    - 3000
  links:
    - redis:redisstore
  labels:
    io.rancher.scheduler.affinity:container_label_soft_ne: io.rancher.stack_service.name=$${stack_name}/$${service_name}
    io.rancher.container.pull_image: always
  privileged: true
  restart: always

redis:
  image: redis:2.8
  container_name: redisstore
  expose:
    - 6379
