lb:
  scale: 1
  load_balancer_config:
    name: lb config
  #   lb_cookie_stickiness_policy:
  #     cookie: sessionID
  #     domain: ibackpacker.com.au
  #     mode: prefix
  health_check:
    port: 42
    interval: 2000
    unhealthy_threshold: 3
    healthy_threshold: 2
    response_timeout: 2000
  default_cert: ibackpacker-wildcard-crt


web:
  scale: 2
  health_check:
    port: 3000
    # Interval is measured in milliseconds
    interval: 2000
    unhealthy_threshold: 3
    # For TCP, request_line needs to be ''
    # TCP Example:
    # request_line: ''
    # request_line: GET / HTTP/1.0
    healthy_threshold: 2
    # Response timeout is measured in milliseconds
    response_timeout: 2000
